### ISSUE TITLE
pcr会战分数改版导致BOSS进度推算错误

### ISSUE THREAD

**Issue by wosiwq** [pcrbot/clanrank#16]
修改 [boss.py#24](https://github.com/pcrbot/clanrank/blob/e12185240882401a21d488dbe7305e1870ecdb1b/boss.py#L24) 行为 `score_left = score / 100000` 可以解决 但是源站也正在修改中，不知道是否会影响最终结果，故暂不提交PR，仅提交issue

**Comment by var-mixer** [comment]
看了下源站也挺混乱的......前几名显示的进度是5周目，然后拉到后面低分的就是几十周目了。可能是根据大小来猜测有没有出BUG？等着源站修复吧。

**Comment by wosiwq** [comment]
源站混乱是因为 [#L301](https://github.com/Kengxxiao/Kyouka/blob/15891186fcd2e6bdf8131b1caa04a43d033d6c26/index.js#L301) 现在更新后已经恢复正常

**Comment by wosiwq** [comment]
但因为此处修改预计以后的公会战A面三王以前都会混乱
