### ISSUE TITLE
查询公会如果有多个结果的时候机器人发送不出来

### ISSUE THREAD

**Issue by H-K-Y** [pcrbot/clanrank#3]
10:41:46 [INFO] [BOT 361233717] Group(823820675) <- 第1条信息：\n公会名称：上弦月\n总人数：30\n会长名：月见莉莉娅\n会长UID：1343040248366\n公会排名：114\nBOSS进度：9周目4王 [11411019/12000000]  95.09%\n\n第2条信息：\n公会名称：上弦花月醉伊人\n总人数：30\n会长名：叶秋痕（阿矿奥利给\n会长UID：1363342891538\n公会排名：3820\nBOSS进度：8周目3王 [9761706/10000000]  97.62%\n\n第3条信息：\n公会名称：上弦月\n总人数：30\n会长名：如沐丶秋枫\n会长UID：1234357880395\n公会排名：13475\nBOSS进度：5周目3王 [1545423/10000000]  15.45%\n\n查询有120秒冷却

查询公会的时候如果查到多个结果，机器人后台显示已经发送，但是群里没有显示消息，
如果只有一个结果群里就能正常显示出来
查询排名和分数线也没有问题

我是用的是mirai

**Comment by H-K-Y** [comment]
似乎又没事了，尴尬

**Comment by var-mixer** [comment]
这个问题我也会遇到，这种查询结果有非常多的数字的长消息更容易被吞。现在已经支持了消息模板，你可以通过修改源代码来自定义推送格式，比如只显示公会名称和公会排名，以缩短长消息。但是需要注意更新本插件时`git pull`会造成冲突会覆盖掉本地模板。

下次会战前考虑把长消息分割为多条发送。另外考虑把推送格式移动到HoshinoV2的统一配置目录`config`中来配置。
